### ISSUE TITLE
Problem cloning the repo

### ISSUE THREAD

**Issue by AntonPetrov** [ucfcbb/RNAMotifProfile#1]
👋 Hello @mahfuz75 @ucfcbb!

This project looks really exciting - I cannot wait to try it out. However, when I attempted to clone the repo but I got an error:

```
git clone https://github.com/ucfcbb/RNAMotifProfile.git
Cloning into 'RNAMotifProfile'...
remote: Enumerating objects: 5883, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 5883 (delta 3), reused 10 (delta 3), pack-reused 5866
Receiving objects: 100% (5883/5883), 49.57 MiB | 8.50 MiB/s, done.
Resolving deltas: 100% (743/743), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'data/pdb_fasta/6HA1_A.rmsx.nch'
  'data/pdb_fasta/6HA1_a.rmsx.nch'
```

It seems like the filenames cannot be case-sensitive (`_a` and `_A`) on Macs which causes a collision (see this [StackOverflow thread](https://stackoverflow.com/questions/63468346/case-sensitive-path-collisions-on-case-insensitive-file-system-when-i-do-git-clo) for example). 

Could you please advise about the best way to install the software on Mac?

**Comment by mahfuz75** [comment]
Hello @AntonPetrov,

Thank you so much for your interest in our work. The current version of RNAMotifProfile is implemented using Python in a 64-bit Linux environment. So, the directory structure and filenames are compatible with any Linux OS. However, it might not be compatible with Windows and/or MacOS.

It'd be great if you could use a Linux machine to check on the code while we are working on this to make it compatible with other operating systems.

**Comment by mahfuz75** [comment]
Hello @AntonPetrov,
We have added MacOS compatibility to our code. Hope it will work flawlessly on Mac from now on.
Thanks.
